### ISSUE TITLE
Graphics, voxelgrid defination is missing

### ISSUE THREAD

**Issue by chinmay1148** [weders/NeuralFusion#1]
Please  add steps about deps required for the codebase
I got this error for while test.py
Error:
File "~/Working/Projects/NeuralFusion/training/database.py", line 7, in <module>
    from graphics.voxelgrid import FeatureGrid, Voxelgrid
ModuleNotFoundError: No module named 'graphics'

I add the deps and scripts folder to the repo and build the deps as in routedfusion using install_docker.sh, then ran the test.py got this error.

 File "~/Working/Projects/NeuralFusion/deps/graphics/src/graphics/voxelgrid.py", line 28, in __init__
    self._data = np.zeros(self._shape)
TypeError: only integer scalar arrays can be converted to a scalar index

Is there a difference in voxelgrid defination ?

**Comment by fengziyue** [comment]
Hi @chinmay1148 
Have you solved this problem?

**Comment by chinmay1148** [comment]
I discontinued the work.
